name: menacees
description: High-school senior project for Rachel - Menacées! Espèces en danger  (i.e. Threatened! Endangered species)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  csv: ^4.0.0
  map_view: ^0.0.14

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/data/species.csv
   - assets/details/albatros-galapagos-icon.png
   - assets/details/antilope-saiga-icon.png
   - assets/details/beluga-saint-laurent-icon.png
   - assets/details/chabot-tete-courte-icon.png
   - assets/details/dhole-icon.png
   - assets/details/loutre-cali-icon.png
   - assets/details/martre-amerique-icon.png
   - assets/details/okapi-icon.png
   - assets/details/rhino-java-icon.png
   - assets/details/rhino-indian-icon.png
   - assets/details/tamarin-pinche-icon.png
   - assets/details/vipere-milos-icon.png
   - assets/markers/albatros-galapagos-icon.png
   - assets/markers/antilope-saiga-icon.png
   - assets/markers/beluga-saint-laurent-icon.png
   - assets/markers/chabot-tete-courte-icon.png
   - assets/markers/dhole-icon.png
   - assets/markers/loutre-cali-icon.png
   - assets/markers/martre-amerique-icon.png
   - assets/markers/okapi-icon.png
   - assets/markers/rhino-java-icon.png
   - assets/markers/rhino-indian-icon.png
   - assets/markers/tamarin-pinche-icon.png
   - assets/markers/vipere-milos-icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
